/* Copyright 2015 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "iotjs_def.h"


namespace iotjs {

//
// strings in iotjs built-in scripts
//
#define JERRY_MAGIC_STRING_ITEMS \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_PROCESS, "process") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_GLOBAL, "global") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_MODULE, "module") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_GLOBAL_U, "GLOBAL") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_Native_UL, "Native") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_DOTJS, ".js") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_EXPORTS, "exports") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CACHE, "cache") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_NATIVE, "native") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_START_IOTJS, "start_iotjs") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_INIT_GLOBAL, "init_global") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_INIT_TIMERS, "init_timers") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_INIT_PROCESS, "init_process") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_MODULEDIRS, "moduledirs") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_MODULE_UL, "Module") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_PLATFORM, "platform") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_RUNMAIN, "runMain") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_REQUIRE, "require") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ROOT, "root") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CONSOLE, "console") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_BINDING, "binding") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_BUFFER_UL, "Buffer") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_BUFFER, "buffer") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CALLBACK, "callback") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CALLBACKS, "callbacks") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ID, "id") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_EMIT, "emit") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CODE, "code") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_EXIT, "exit") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_EXITCODE_UL, "exitCode") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_KEY, "key") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ON, "on") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ONCE, "once") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_LISTENER, "listener") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_LISTENERS, "listeners") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_EVENTS, "events") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_U_EVENTS, "_events") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_EVENTEMITTER_U, "EventEmitter") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_INITPROCESS, "initProcess") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_INITPROCESSEXIT_UL, "initProcessExit") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_INITPROCESSNEXTTICK_UL, \
                                                  "initProcessNextTick") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_INITPROCESSEVENTS, "initProcessEvents") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_REMOVELISTENER_U, "removeListener") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_TYPE, "type") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ARG1, "arg1") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ARG2, "arg2") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_HANDLER, "handler") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ADDLISTENER_UL, "addListener") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_INDEXJS, "index.js") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SPACKAGEJSON, "/package.json") \
  \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_TIMERS, "timers") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_FILENAME, "filename") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_COMPILE, "compile") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SCRIPT, "script") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_WRAPPER, "wrapper") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SOURCE, "source") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_TEXT, "text") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_FN, "fn") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_OFFSET, "offset") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_UTIL, "util") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_READ, "read") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_WRITE, "write") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_OPEN, "open") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CLOSE, "close") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_PARENT, "parent") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_COPY, "copy") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_UWRITE, "_write") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_LOAD, "load") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SELF, "self") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_MAIN, "main") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_PATH, "path") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ERR, "err") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_STAT, "stat") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_FLAG, "flag") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_FD, "fd") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SC_LR, "(") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SC_RR, ")") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SC_BRACECLOSE, "});") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SC_CLOSE, ");") \
  \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_STR, "str") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_LIST, "list") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_POS, "pos") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_POSITION, "position") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_UTF8, "utf8") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_START, "start") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_END, "end") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SUBJECT, "subject") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ENCODING, "encoding") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ALLOC, "alloc") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_TIMEOUT, "timeout") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_DELAY, "delay") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_REPEAT, "repeat") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_INTERVAL, "interval") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SETTIMEOUT_UL, "setTimeout") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SETINTERVAL_UL, "setInterval") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CLEARTIMEOUT_UL, "clearTimeout") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CLEARINTERVAL_UL, "clearInterval") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_INITNEXTTICK_UL, "initNextTick") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_NEXTTICKQUEUE_UL, "nextTickQueue") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_NEXTTICK_UL, "nextTick") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_UONNEXTTICK_UL, "_onNextTick") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_NATIVEMOD_UL, "nativeMod") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_WRAP, "wrap") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ISBUFFER_UL, "isBuffer") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ISNUMBER_UL, "isNumber") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ISSTRING_UL, "isString") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ISUNDEFINED_UL, "isUndefined") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ISNULL_UL, "isNull") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ISNULLORUNDEFINED_UL, "isNullOrUndefined") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ISOBJECT_UL, "isObject") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ISFUNCTION_UL, "isFunction") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ISMAIN_UL, "isMain") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ISDIRECTORY_UL, "isDirectory") \
  \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_A, "a") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_B, "b") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_C, "c") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_D, "d") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_E, "e") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_F, "f") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_I, "i") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_J, "j") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_K, "k") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_T, "t") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ARG, "arg") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ENC, "enc") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_REMAINING, "remaining") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_INHERITS, "inherits") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CTOR, "ctor") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_FS, "fs") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CWD, "cwd") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ENV, "env") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_HOME_U, "HOME") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_DIR, "dir") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_DIRS, "dirs") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_STATS, "stats") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_EX, "ex") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ARGV, "argv") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ARGC, "argc") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_UID, "uid") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_GID, "gid") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_DEV, "dev") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_MODE, "mode") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SLASH, "/") \
  \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SUPERCTOR_UL, "superCtor") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_FILEPATH, "filepath") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_TRYPATH_UL, "tryPath") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_PACKAGEPATH, "packagepath") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_BYTELENGTH, "byteLength") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_JSONPATH, "jsonpath") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_JSONPARSE_UL, "JSONParse") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_COMPILENATIVEPTR_UL, "compileNativePtr") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_O_RDONLY_U, "O_RDONLY") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_O_SYNC_U, "O_SYNC") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_O_RDWR_U, "O_RDWR") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_O_CREAT_U, "O_CREAT") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_O_TRUNC_U, "O_TRUNC") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_O_APPEND_U, "O_APPEND") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_O_WRONLY_U, "O_WRONLY") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_O_EXCL_U, "O_EXCL") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_S_IFDIR_U, "S_IFDIR") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_S_IFMT_U, "S_IFMT") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CONSTANTS, "constants") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CONVERTFLAGS, "convertFlags") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_NLINK, "nlink") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_RDEV, "rdev") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_BLKSIZE, "blksize") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SIZE, "size") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_BLOCKS, "blocks") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_FLAGS, "flags") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_STATOBJ, "statobj") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CREATESTAT_UL, "createStat") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_S_NODE_MODULES_S, "/node_modules/") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_NATIVE_SOURCES, "native_sources") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_UTOSTRING, "_toString") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SETUPBUFFERJS_UL, "setupBufferJs") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_WWWWRAP_UL, "wwwwrap") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_KMAXLENGTH_UL, "kMaxLength") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CONCATDIR, "concatdir") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_RLIST, "rlist") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_RESOLVEDIRECTORIES_UL, "resolveDirectories") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_RESOLVEFILEPATH_UL, "resolveFilepath") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_DIRECTORIES, "directories") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_PKGSRC_UL, "pkgSrc") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_READSOURCE_UL, "readSource") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_PKGMAINFILE_UL, "pkgMainFile") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_RESOLVEMODPATH_UL, "resolveModPath") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_STATPATH_UL, "statPath") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_STATSYNC_UL, "statSync") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_STATS_U, "Stats") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_FSBUILTIN_UL, "fsBuiltin") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_MODPATH_UL, "modPath") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SETMODULEDIRS_UL, "SetModuleDirs") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_REQUIREFORTHIS_UL, "requireForThis") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_OPENSYNC_UL, "openSync") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_CB_WRAP_UL, "cb_wrap") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_BYTESREAD, "bytesRead") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_READSYNC, "readSync") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_INO, "ino") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_R, "r") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_RS, "rs") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SR, "sr") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_R_P, "r+") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_RS_P, "rs+") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_SR_P, "sr+") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_W, "w") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_WX, "wx") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_XW, "xw") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_W_P, "w+") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_WX_P, "wx+") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_XW_P, "xw+") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_AX, "ax") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_XA, "xa") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_A_P, "a+") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_AX_P, "ax+") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_XA_P, "xa+") \
  \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_BAD_ARGUMENTS_U, "Bad arguments") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_NO_MODULE_FOUND, "No module found") \
  \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_TEMP1, "temp1") \
  \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_ARTIK, "artik") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_NUTTX, "nuttx") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_MBED, "mbed") \
  MAGICSTR_EX_DEF(MAGICSTREXITEM_EDISON, "edison")

//
// declare string items
//
#define MAGICSTR_EX_DEF(NAME, STRING) \
  static const char jerry_magic_string_ex_ ## NAME[] = STRING;

JERRY_MAGIC_STRING_ITEMS

#undef MAGICSTR_EX_DEF


//
// declare strings length array
//
static const jerry_api_length_t magic_string_lengths[] =
{
#define MAGICSTR_EX_DEF(NAME, STRING) \
  (jerry_api_length_t)(sizeof(jerry_magic_string_ex_ ## NAME) - 1u),

  JERRY_MAGIC_STRING_ITEMS

#undef MAGICSTR_EX_DEF
};


//
// declare strings table
//
static const jerry_api_char_ptr_t magic_string_items[] =
{
#define MAGICSTR_EX_DEF(NAME, STRING) \
  (const jerry_api_char_ptr_t)jerry_magic_string_ex_ ## NAME,

  JERRY_MAGIC_STRING_ITEMS

#undef JERRY_MAGIC_STRING_DEF
};


void InitJerryMagicStringEx(void) {
  uint32_t num_magic_string_items = (uint32_t)(sizeof(magic_string_items)
                                    / sizeof(jerry_api_char_ptr_t));
  jerry_register_external_magic_strings(magic_string_items,
                                        num_magic_string_items,
                                        magic_string_lengths);
}

} // namespace iotjs
